# Site settings
title: CEHS Coding Club
email: cehscoding@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  CEHS Coding is a student led club for learning programming.
twitter_box: >
  <a class="twitter-timeline" data-dnt="true" href="https://twitter.com/nrobinson2000" data-widget-id="656147837043015680">Tweets by @nrobinson2000</a>
  <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://cehs.github.io" # the base hostname & protocol for your site
twitter_username: CEHSCoding
github_username:  cehs


# nav_message: >
#
#   <h3>About my Project:</h3>
#   <ul>
#   <li>My project is a practical demonstration of the Internet of Things that utilizes arduino-like boards to create a wifi-connected device. <strong> Read the links above to learn about my project.</strong></li>
#   <br>
#   <li>This website is hosted on GitHub pages on my GitHub account.  You can see the <a href="https://github.com/nrobinson2000/nrobinson2000.github.io">source code here.</a></li>
#   </ul>


# Build settings
markdown: kramdown
